### PR TITLE
Update document to use --debug option when deploy BookInfo app

### PR DESCRIPTION
**Pull request by incfly**
This is required for mutual TLS verification, where we asks user to login into envoy container and `curl`. program curl is only installed in docker.io/istio/proxy_debug:.*.

See https://github.com/istio/istio/issues/3399 for background.

### CODE REVIEW

**Comment by incfly** [comment]
I verified in the lastest istio 0.6, this change makes mTLS tutorial works again.

**Comment by wattli** [comment]
@ldemailly , should we use debug version in bookinfo demo? Some of the demo requires libs that only exist in debug version, like 'curl'

**Comment by wattli** [comment]
https://github.com/istio/istio/issues/3399 is the issue

**Comment by ldemailly** [comment]
yes sounds good; for bookinfo performance should not matter

**Pull request merged**
