### PR TITLE
New authn diagram

### PR DESCRIPTION
**Pull request by oaktowner**
at @geeknoid's suggestion, doing one PR per diagram. Here's a new diagram for /content/docs/concepts/security/authn

### CODE REVIEW

**Comment by geeknoid** [comment]
Dan, could you sync your tree and push your PR again? Right now, this PR reupdates previous diagrams as you can see in the Files Changed tab.

So

git pull upstream
git rebase upstream/master

**Comment by linsun** [comment]
Re arch diagram (the last one), @oaktowner (thanks for updating the diagrams!)is it possible to add istio ingress gateway and egress gateway in there?

**Comment by oaktowner** [comment]
Closing this -- will do one PR per file going forward

**Pull request closed without merging**
