### PR TITLE
Add a platform setup section and link it in helm install page

### PR DESCRIPTION
**Pull request by wattli**
Otherwise people will not set up corresponding environment and the installation will fail.

For instance, you need to set up RBAC https://preliminary.istio.io/docs/setup/kubernetes/quick-start/#google-kubernetes-engine in GKE.

### CODE REVIEW

**Comment by wattli** [comment]
I agree and I can work on it, but not sure everyone like this idea or we can just make a section called 'Platform setup' in that page, I feel the latter is safer. @geeknoid

**Comment by sdake** [comment]
ya please have @geeknoid weigh in.

Cheers
-steve

**Comment by wattli** [comment]
Cool, i will ping back when it's done.

**Comment by wattli** [comment]
@geeknoid , PTAL

**Comment by geeknoid** [comment]
Looks good.

@sdake?

**Pull request merged**
