### PR TITLE
Fix inconsistent header use in this doc.

### LINKED ISSUE #1116: Issue with TOC (in _docs/setup/kubernetes/sidecar-injection.md and elsewhere)
https://istio.io/docs/setup/kubernetes/sidecar-injection.html

I wanted to hyperlink the "Pod Spec Requirements" section but I can't

the toc is missing the top level entries

screen shot 2018-03-28 at 4 45 14 pm

any idea why @geeknoid  ?

( a work around I suppose is to add 1 # to every # xxx but is that an issue site wide?)

### PR DESCRIPTION
**Pull request by geeknoid**
Fixes #1116 

Staging: https://geeknoid.github.io/istio.github.io/docs/setup/kubernetes/sidecar-injection.html

### CODE REVIEW

**Comment by ldemailly** [comment]
"Injection" should also be in the toc no ?

**Comment by ldemailly** [comment]
+1

**Comment by ldemailly** [comment]
any reason you didn't fix the Injection one ?

**Comment by geeknoid** [comment]
Oh _that_. No, no reason. Fix coming up.


On Fri, Mar 30, 2018 at 11:10 AM, Laurent Demailly <notifications@github.com

**Pull request merged**
