### PR TITLE
Revise istio auth description in bookinfo demo

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by wattli** [comment]
@andraxylia

**Comment by wattli** [comment]
@geeknoid

**Comment by andraxylia** [comment]
@rshriram I asked for this change, because the current content is confusing. We either move all "playing with auth" out of the bookinfo into a separate task, or we add the clarification section.

**Comment by wattli** [comment]
@rshriram , agree this page should be clean and the detail should be kept in separate page, and this is exactly what this PR does.

It rewords the auth description a little bit by 1) adding more links to auth page; 2) updating the presentation logic

@andraxylia , FYI

**Comment by rshriram** [comment]
@andraxylia @frankbu said he was going to take a crack at moving the auth content into the Auth page and cleaning this up. So, for the moment, I am going to approve this. 

@wattli can you hold off on any more changes to this doc, while @frankbu moves this content in proper way to the istio auth task?

**Comment by wattli** [comment]
@rshriram , the content is tightly related to the demo, hopefully it's not too difficult for audiences to see it.

@frankbu, please cc me the PR, thanks.

**Pull request merged**
