### PR TITLE
Update distributed tracing doc to reflect changes in 0.8.0

### PR DESCRIPTION
**Pull request by objectiser**
Fixes https://github.com/istio/istio/issues/5971

This PR also includes a minor formatting fix in the quick start page.

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit aaea14b8068f6d78bd1d956326ec72f12098efd8

https://app.netlify.com/sites/preliminary-istio/deploys/5b11a0d8b13fb137a55243cc

**Comment by objectiser** [comment]
/assign @linsun 

Someone may need to review the GKE setup instructions and update as necessary (e.g. console image). I've just changed the tracing related refs/image.

**Comment by adriancole** [comment]
so there was template drift.. to address this you decided to delete zipkin. This was done by a jaeger committer.

@linsun I doubt you meant this, but this action is beyond insensitive. Consider jaeger has skin in the game of deleting zipkin. Then consider how nice it is to delete zipkin off their own formats! 

This has already caused confusion in the user base. If this is about helm chart there was already one from the community. https://github.com/Financial-Times/zipkin-helm

Consider there's only one full time staff in zipkin, we rely in part on the kindness of staffed projects like yours to do the right thing. Volunteers do quite a lot, but can't be tasked to track everything.

Does anyone have time to make this right? Restore the docs, fix the template? You might be able to fix this quicker. Meanwhile I will try to help source someone.

**Comment by objectiser** [comment]
@adriancole The switch from zipkin to jaeger backend was actually done by @douglas-reid in this PR https://github.com/istio/istio/pull/5656.

I had previously tried to include [Jaeger helm chart](https://github.com/istio/istio/pull/5098) alongside Zipkin, but the PR was not accepted.

It has long been the intention to support multiple tracing backends in Istio's helm chart, so would be good to have zipkin supported again. If I get some free time I will try to add it in - but if you find someone else that would be great.

**Comment by adriancole** [comment]
@objectiser appreciate your letting know the background. consider you helping to remove all references is something not quite cool, even if others did worse. Appreciate for sure if you can help make this right. I hope you won't get blocked by google folks or otherwise again

**Comment by douglas-reid** [comment]
@adriancole if I may speak for @costinm and @mandarjog, iirc, around the 0.8 timeframe, there was concern with the startup time of the zipkin add-on, as this impacted overall runtime of end-to-end tests, etc. I was asked to switch to the default add-on to jaeger, as it was felt that this would improve the situation. I don't know if the switch ended up having the intended impact, as the details of that release have been purged from my memory.

As @objectiser relates, there remains a strong intention to support multiple tracing integrations. Unfortunately, during release crunches, some of our best intentions go unfulfilled -- and we find ourselves in situations such as this.

As I was the one that ultimately submitted the PR that led to this situation, I will take ownership of trying to restore. I will add you as a reviewer to ensure that I'm using the most recent images, etc.

**Comment by adriancole** [comment]
@douglas-reid in my book, once resolved, all-good. Appreciate the frankness. I'll ask folks who were confused to review your work.

**Comment by adriancole** [comment]
This appears to be the PR to resolve this: https://github.com/istio/istio/pull/9910

**Comment by douglas-reid** [comment]
@adriancole I would love to have an integration that we could point to with Skywalking, etc. I've been meaning to get around to documenting, in full, the different ways that Istio can support multiple vendors and formats -- as well as to try to balance the various approaches to integrating different tracing formats and backends (more envoy drivers v. mixer adapters v. opencensus exporters v. ??). If you have some time to spare and are willing to help sort out recommendations, etc., I would appreciate any advice / guidance / feedback you are willing to provide.

In a similar vein, I've been trying to get traction on a full Istio API for controlling tracing in general (see: https://github.com/istio/api/pull/363). As of now, all we have are env vars and install options. Any help there would be doubly-welcome.

I'm not sure I can offer much c++ help at the moment, but I'll definitely keep that in mind should the opportunity arise.

Thanks again for engaging and helping to push us forward.

**Comment by adriancole** [comment]
advice is cheap :) yeah the ones mentioned accept zipkin format would be
easiest as you have to do similar to jaeger or zipkin to drop them in.

Ones that can't might be more tricky or end up a backend to trace forwarder
like pitchfork. You could imagine that pitchfork could send zipkin data to
Amazon X-Ray for example. Zipkin's server can proxy to x-ray as well.

can't do much more than advice right now but hope it helps.

**Pull request merged**
