### PR TITLE
Update circuit break use existing file.

### PR DESCRIPTION
**Pull request by gyliu513**

### CODE REVIEW

**Comment by frankbu** [comment]
There is a new version of this task: https://github.com/istio/istio.github.io/blob/master/_docs/tasks/traffic-management-v1alpha3/circuit-breaking.md

**Comment by geeknoid** [comment]
Should we go ahead and merge this?

**Comment by frankbu** [comment]
@geeknoid, I'm not sure it makes sense to make this change in the soon to be deprecated version of the task. The corresponding change to the v1apha3 version of the task, however, prereqs creating the yaml file in istio/istio. Personally, I would just leave it as is for now.

**Comment by geeknoid** [comment]
@gyliu513 should we close this per Frank's comments?

**Comment by gyliu513** [comment]
As we need to maintain different istio versions, so I think that we may still need this to be merged. @frankbu @geeknoid

**Comment by geeknoid** [comment]
@frankbu Frank, what do you think?

**Comment by frankbu** [comment]
I don't have strong opinion, but I wouldn't do it, since this is going to get tossed soon anyway. Starting with 0.8, we are going to point people at v1alpha3.

**Comment by geeknoid** [comment]
All right, let's just put it in. It doesn't hurt.

**Pull request merged**
