### PR TITLE
Add namespace to port forward command for zipkin/jaeger and jaeger deployment

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
resolves istio/issues#73

**Comment by linsun** [comment]
for the apply cmd, should we have namespace istio-system in the yaml so that user doesn't need to specify that?  That will be consistent with how we install the other add-ons.

**Comment by objectiser** [comment]
@linsun The template is part of the jaeger project, so independent of istio, so would prefer to just maintain the template in one place for general use.

**Comment by objectiser** [comment]
Also resolves istio/istio#936

**Pull request merged**
