### PR TITLE
to fix the #1324

### PR DESCRIPTION
**Pull request by olegchorny**

### CODE REVIEW

**Comment by olegchorny** [comment]
Sorry guys, I signed CLA, I hope we can proceed now.

**Comment by olegchorny** [comment]
This were changed and I've submitted another #1404 to fix this issue.

**Comment by geeknoid** [comment]
Could you please rebase, resolve conflicts, and resubmit?

Thanks.

**Comment by olegchorny** [comment]
This issue has been fixed by another pull request already, I'm closing this PR, thanks.

**Pull request closed without merging**
