### PR TITLE
New request flow diagram

### PR DESCRIPTION
**Pull request by oaktowner**
Used on https://istio.io/docs/concepts/traffic-management/request-routing/

### CODE REVIEW

**Comment by sdake** [comment]
@rshriram can you take a  quick look at this updated diagram: https://deploy-preview-1930--preliminary-istio.netlify.com/docs/concepts/traffic-management/ServiceModel_RequestFlow.svg

**Comment by rshriram** [comment]
replace ingress proxy with ingress gateway for consistency with other diagrams.
Add an optional egress gateway

**Comment by geeknoid** [comment]
Please update markdown to have the proper width and ratio values for revised images.

**Comment by linsun** [comment]
Agree with @rshriram 's comment, unless this diagram is intended to show k8s ingress can be configured to use istio enabled services which is one of our Istio scenario too @oaktowner

**Comment by sdake** [comment]
@geeknoid I am unable to tell if the ratios are correct - can you provide a bit of tutorial on how to validate these things?  Otherwise, @rshriram 's review comments have been addressed.

/lgtm

**Pull request merged**
