### PR TITLE
Flip the switch! Re-enable the front page, and some last minute minor tweaks to the blog post.

### PR DESCRIPTION
**Pull request by smawson**
- Blog post date corrected, plus some links fixed.
- index.html replaced with true-index.html content for landing page.

### CODE REVIEW

**Comment by smawson** [comment]
FYI submitting this at 7 AM tomorrow.

**Comment by ldemailly** [comment]
2 minor things:

GitHub link should be http://github.com/istio/issues/issues  so it opens on the list of existing issues
And Twitter should be IstioMesh (capitalization helps)

**Comment by rshriram** [comment]
@smawson as part of this PR, can you also fix the link in the blog post to what everyone has seen in the google doc?

**Comment by rshriram** [comment]
https://istio.io/blog/istio-service-mesh-for-microservices.html

**Comment by rshriram** [comment]
We have given thsi link to everyone

**Comment by rshriram** [comment]
Oh nm.. its already set to the right link. I thought I saw @geeknoid asking you to change the link.
LGTM

**Comment by ldemailly** [comment]
the errors should go away once partners blogs are up:
  *  External link https://blog.openshift.com/red-hat-istio-launch failed: 404 No error
  *  External link https://github.com/istio/istio.github.io/edit/master/_posts/2017-05-24-0.1-announcement.md failed: 404 No error
  *  External link https://weave.works/docs/tutorials/istio/istio failed: 404 No error
  *  External link https://www.datawire.io/istio-and-datawire-ecosystem failed: 404 No error
  *  External link https://www.projectcalico.org/welcoming-istio-to-the-kubernetes-networking-community failed: 404 No error

alternatively you can add `data-proofer-ignore` attribute or div (https://github.com/gjtorikian/html-proofer#ignoring-content) but in this case we can just squash and merge anyway when we want

**Comment by rshriram** [comment]
This link error can be ignored
`External link https://github.com/istio/istio.github.io/edit/master/_posts/2017-05-24-0.1-announcement.md`

**Comment by ldemailly** [comment]
maybe some or all instances of "release" or "releasing" should be links to
https://github.com/istio/istio/releases
which will also get a chance for people to star that repo (to @rshriram's point)

**Comment by zinuga** [comment]
Weave link should be this one
https://www.weave.works/blog/istio-weave-cloud

**Comment by rshriram** [comment]
@smawson please rebase

**Pull request closed without merging**
