### PR TITLE
Revert "Improve consistency of the coloring of a few elements with the site theme"

### PR DESCRIPTION
**Pull request by ldemailly**
Reverts istio/istio.github.io#851

fixing #852

### CODE REVIEW

**Comment by ldemailly** [comment]
cc @geeknoid 

also that light blue when mousing over is weird anyway

**Comment by ldemailly** [comment]
screen shot 2018-01-07 at 8 28 15 pm

**Comment by geeknoid** [comment]
That light blue when mousing over is how it has been, nothing changed that.

**Comment by ldemailly** [comment]
check istio.io or the archives and you will see it isn’t 

in general testing changes minimally helps

**Pull request merged**
