### PR TITLE
Explain that the 10s mentioned timeout is hardcoded. Fixes #1213.

### LINKED ISSUE #1213: Question about the fault injection description.
In the documentation, there is a phase described "we will inject a 7s delay between the reviews:v2 and ratings microservices, for user “jason”. **Since the reviews:v2 service has a 10s** timeout for its calls to the ratings service, we expect the end-to-end flow to continue without any errors"
I am not clear where can get the more information about "Since the reviews:v2 service has a 10s? Is related to the 7s injected?"
Thanks a lot.

### PR DESCRIPTION
**Pull request by ymesika**

### CODE REVIEW

**Comment by ymesika** [comment]
Thanks, updated the other file too.

**Comment by linsun** [comment]
@ymesika could you resolve the conflict?

**Pull request merged**
