### PR TITLE
re translate /zh/blog/2018/egress-tcp/ page

### PR DESCRIPTION
**Pull request by trainyao**
for changes of content/blog/2018/egress-tcp/index.md file between commit fd290dc73e4fd2ea8bba93453b03960e1f71645f and 82eb2c21a36b751677e3472c9dce4a5617d3d0a5

### CODE REVIEW

**Comment by fleeto** [comment]
连接检查一下？

```
- ./public/zh/blog/2018/egress-tcp/index.html
  *  internally linking to /zh/docs/reference/config/istio.networking.v1alpha3/#虚拟服务, which does not exist (line 40)
     <a href="/zh/docs/reference/config/istio.networking.v1alpha3/#%E8%99%9A%E6%8B%9F%E6%9C%8D%E5%8A%A1">虚拟服务(virtual service)</a>
  *  linking to internal hash #TCP流量的服务入口 that does not exist (line 60)
     <a href="#TCP%E6%B5%81%E9%87%8F%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%85%A5%E5%8F%A3">下面</a>
  *  trying to find hash of /zh/docs/reference/config/istio.networking.v1alpha3/#虚拟服务, but /root/site/public/zh/docs/reference/config/istio.networking.v1alpha3 does not exist (line 40)
     <a href="/zh/docs/reference/config/istio.networking.v1alpha3/#%E8%99%9A%E6%8B%9F%E6%9C%8D%E5%8A%A1">虚拟服务(virtual service)</a>
```

**Comment by trainyao** [comment]
已处理 @fleeto

**Pull request merged**
