### PR TITLE
Synch example with attribute vocabulary

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by metacosm** [comment]
I signed it!

**Comment by geeknoid** [comment]
@metacosm Could you accept the CLA please? Otherwise, we can't take your PR.

Thanks.

**Comment by metacosm** [comment]
I'm afraid I'm going to have to re-do this PR since GitHub is not signing my commit with the proper email despite setting it as my primary email.

**Comment by metacosm** [comment]
I signed it!
(Last attempt)

**Comment by metacosm** [comment]
I guess it's not going to work… CLA page correctly says that I'm covered by the Red Hat agreement but for some reason the bot doesn't think I am.

**Comment by metacosm** [comment]
@geeknoid I've opened a new one (#957), was trying avoiding to clone locally for this minor but I guess I didn't have a choice…

**Pull request closed without merging**
