### PR TITLE
Translate fix zh links

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by loverto** [comment]
https://deploy-preview-2105--preliminary-istio.netlify.com/zh/docs/concepts/policies-and-telemetry/#%E9%85%8D%E7%BD%AE%E6%A8%A1%E5%9E%8B

**Comment by loverto** [comment]
image

**Comment by fleeto** [comment]
@loverto reference hasn't been translated yet, so  we have to keept it.

**Comment by fleeto** [comment]
#1923 #2014 
All internal links in Chinese version except 'references', had been converted to '/zh' style.

**Pull request merged**
