### PR TITLE
split tasks into categories

### PR DESCRIPTION
**Pull request by rshriram**

### CODE REVIEW

**Comment by rshriram** [comment]
image

**Comment by rshriram** [comment]
@Rachel-Graham FYI. Just moving content around. If there is content level edits in the index, let me know and I will make changes subsequently

**Comment by rshriram** [comment]
@Rachel-Graham

**Comment by Rachael-Graham** [comment]
@rshriram LGTM. (PS I have an extra 'a' in there--that's why you couldn't tag me :) rachael-graham)

**Pull request merged**
