### PR TITLE
translating traffic management overview into Chinese

### PR DESCRIPTION
**Pull request by rootsongjc**
- translating traffic management overview
- modify docs index
- add traffic management index

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit 00fc53d6abce8fe8cf38175f5ca3b62aebc784a7

https://app.netlify.com/sites/preliminary-istio/deploys/5b2ba7c20733d5690ab3d46b

**Comment by rootsongjc** [comment]
Build successfully but deployed failed, got these errors:
```
9:28:46 PM: Starting to deploy site from 'public'
9:33:26 PM: Failing build: Failed to deploy site
9:33:28 PM: failed during stage 'deploying site': Failed to execute deploy: Upload cancelled: docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html
9:33:30 PM: Finished processing build request in 5m58.44540951s
```
I didn't change anything in `docs/reference/config/policy-and-telemetry/adapters/fluentd/index.html` What's wrong with this?

**Comment by geeknoid** [comment]
Looks like a hiccup in Netlify, unrelated to your changes. I restarted the thing, hopefully it'll work this time around.

**Comment by geeknoid** [comment]
@fleeto Please review.

**Pull request merged**
