### PR TITLE
Modify yaml to fix the error from istioctl

### PR DESCRIPTION
**Pull request by linsun**
https://github.com/istio/istio.github.io/issues/672#issuecomment-338002266

https://github.com/istio/istio.github.io/issues/672

### CODE REVIEW

**Comment by juliaaano** [comment]
Using kubectl instead of istioctl means the yaml file won't be validated. Is this the desired outcome for this? I believe the right fix would be adding the required field to that file, so it pleases istioctl's validation.

**Comment by linsun** [comment]
good suggestion!  The error msg was not helpful but I figured it out and tested it.  PTAL @rshriram @wattli

**Pull request merged**
