### PR TITLE
Should "openned" be a spelling mistake?

### PR DESCRIPTION
**Pull request by chenkunyun**
In AWS (w/Kops) section:
"openned" should be "opened"?

### CODE REVIEW

**Comment by chenkunyun** [comment]
I signed it!

**Comment by chenkunyun** [comment]
I signed it! again!

**Comment by sdake** [comment]
@chenkunyun click the "merge to master" button to the right of  "This branch is out-of-date with the base branch" or rebase please.

TIA :)
-steve

**Comment by chenkunyun** [comment]
@sdake 
I saw "Your tests failed on CircleCI". Seems there's a 404 error in your CircleCI:

 https://github.com/istio/istio/blob/master/pilot/docker/prepare_proxy.sh failed: 404 No error

**Pull request merged**
