### PR TITLE
Trans help/ops/setup into Chinese

### PR DESCRIPTION
**Pull request by DavadDi**
fix format

### CODE REVIEW

**Comment by rootsongjc** [comment]
@DavadDi CI failed.
```
- ./public/zh/help/ops/setup/validation/index.html
  *  linking to internal hash #invalid-configuration-is-accepted that does not exist (line 1863)
     <a href="#invalid-configuration-is-accepted">verify webhook
configuration</a>
  *  linking to internal hash #invalid-configuration-is-accepted that does not exist (line 1870)
     <a href="#invalid-configuration-is-accepted">验证 webhook 配置</a>
htmlproofer 3.9.1 | Error:  HTML-Proofer found 2 failures!
LINTING FAILED
Exited with code 1
```
Change the hash tag to Chinese.

**Comment by DavadDi** [comment]
还有些链接需要调整

**Comment by DavadDi** [comment]
@rootsongjc  已经调整完毕，帮忙 review 一下，谢谢

**Comment by DavadDi** [comment]
@rootsongjc  并列单词的问题已经修复。

**Pull request merged**
