### PR TITLE
First pass generating docs from istio/api and istio/mixer

### PR DESCRIPTION
**Pull request by ZackButcher**
I put them in a staging area so we can migrate into their final location incrementally.

I haven't really checked the output at all. There's whole categories of work we need to go correct: enum names lost their underscore separators again, ordering of items in the page is alphabetical, etc.

### CODE REVIEW

**Comment by ZackButcher** [comment]
You can review the new pages rendered here: https://zackbutcher.github.io/istio.github.io/docs/reference/new/

**Comment by frankbu** [comment]
I don't see the new egress rule stuff. Do we need to do something special to add a new proto file https://github.com/istio/api/blob/master/proxy/v1/config/egress_rule.proto ?

**Comment by ZackButcher** [comment]
I forgot to add it - doing that now.

**Comment by ldemailly** [comment]
I thought we agreed to not force merge with link errors... now every PR adds more broken links

**Comment by rshriram** [comment]
We have a ton of work to do to fix the auto generated doc. It's easier to have it in repo for others (who are contributing docs) to fix.

We can look through presubmit and identify broken links for respective PRs, as all broken links from this pr are restricted to a separate folder.

**Comment by rshriram** [comment]
More doc gen woes!! 😭
https://envoyproxy.github.io/envoy/intro/arch_overview/arch_overview.html gets converted into 
https://envoyproxy.github.io/envoy/intro/archOverview/archOverview.html

@ZackButcher 
@mattklein123 you might want to keep track of these as you might hit these issues for envoy-api

**Comment by ldemailly** [comment]
camelCase vs _ rings a bell from 0.1

the list of bad links grew to:
```

- ./_site/docs/reference/new/adapters/denier.html
  *  internally linking to /docs/reference/api/status.html, which does not exist (line 1)
     <a href="/docs/reference/api/status.html">Status</a>
- ./_site/docs/reference/new/destination-policies.html
  *  External link https://envoyproxy.github.io/envoy/intro/archOverview/circuitBreaking.html failed: 404 No error
  *  External link https://envoyproxy.github.io/envoy/intro/archOverview/loadBalancing.html failed: 404 No error
  *  External link https://envoyproxy.github.io/envoy/intro/archOverview/outlier.html failed: 404 No error
- ./_site/docs/reference/new/mixer-config.html
  *  External link https://istio.io/docs/reference/attribute-vocabulary.html failed: 404 No error
- ./_site/docs/reference/new/mixer-service.html
  *  External link https://github.com/istio/api/blob/master/mixer/v1/config/descriptor/valueType.proto failed: 404 No error
  *  internally linking to /docs/reference/api/status.html, which does not exist (line 1)
     <a href="/docs/reference/api/status.html">Status</a>
  *  internally linking to /docs/reference/api/status.html, which does not exist (line 6)
     <a href="/docs/reference/api/status.html">Status</a>
  *  internally linking to /docs/reference/api/status.html.details, which does not exist (line 1)
     <a href="/docs/reference/api/status.html.details">google.rpc.Status.details</a>
  *  linking to internal hash #google.rpc.Code that does not exist (line 1)
     <a href="#google.rpc.Code">google.rpc.Code</a>
  *  linking to internal hash #google.rpc.Code that does not exist (line 1)
     <a href="#google.rpc.Code">google.rpc.Code</a>
```
And I remember fixing some of those in 0.1 too

**Comment by mattklein123** [comment]
Hmm. I think this is probably from the Sphinx upgrade. There is probably a way to revert this behavior. Let me look before you fix the docs. (vs. just prefix change): https://github.com/envoyproxy/envoy/pull/1696/files#diff-93bd81aa3a2f0c02728220a6b46fb58dR15

**Comment by mattklein123** [comment]
?

Where are you seeing this? https://envoyproxy.github.io/envoy/intro/arch_overview/arch_overview.html

**Comment by mattklein123** [comment]
Oh. This is in your doc tool? OK. Sorry. I was super confused.

**Comment by ldemailly** [comment]
not sure why shriram tagged you, enjoy the weekend :)

**Comment by rshriram** [comment]
@mattklein123 If you are planning to generate docs from the protos in envoy-api repo, from that internal tool everyone talks about, you might want to make sure these issues are resolved before hand. :)

**Comment by ZackButcher** [comment]
Ah, I think I found the problem with underscores, and it's on my end! I do a `sed` to replace_snake case with camelCase, which is intended for the proto field names. But the unintended side-effect is removing all underscores.

I'll run another round of doc-gen without that particular `sed` and we can compare.

**Pull request merged**
