### PR TITLE
make a note to check options settings before override it

### PR DESCRIPTION
**Pull request by LillyWu**

### CODE REVIEW

**Comment by LillyWu** [comment]
@sdake Thanks for your comment, and please check the above linked issue and my PR to that issue in repo istio/istio

**Comment by sdake** [comment]
@LillyWu Since values.yaml has not gone through a final API review and we will do that for 1.1, I'll merge this now, but we may remove this in the future if the API review indicates this is no longer necessary.

Hope you understand 👍 

Cheers
-steve

**Comment by sdake** [comment]
Please rebase your patch - the gate is failing and a rebase will resolve the problem.

Cheers
-steve

**Comment by LillyWu** [comment]
@sdake  @linsun already rebased, please review. Thanks

**Pull request merged**
