### PR TITLE
quick start doc translation

### PR DESCRIPTION
**Pull request by rootsongjc**
Add quick start page translation

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit fa84acc1112aab303d19bc01b46705dedc193040

https://app.netlify.com/sites/preliminary-istio/deploys/5b23aeb1dd6a5411692267a6

**Comment by rootsongjc** [comment]
@geeknoid I found some markdown style does not follow the rules in `mdl_style.rb` and fixed them.

**Comment by geeknoid** [comment]
To fix a few issues, including the problem with the broken links when introducing new pages, I revamped the build process for the site. We now use CircleCi to run the linters, and Netlify only does the site publication.

It turns out our spell checker already supports Chinese. I tried turning that on, but it failed because of a typo. Could you uncomment the Chinese spell check line in scripts/lint_site.sh and fix the typo that it reports? With the new build setup, you'll be able to do "make lint" on the command-line to run the spell checker.

Thanks.

**Comment by rootsongjc** [comment]
Is there a glossary that can be excluded from the spelling check? While I run `make lint` there will be such errors:
```bash
docker run -t -i --sig-proxy=true --rm -v /Users/jimmysong/Workspace/github/rootsongjc/istio.github.io:/site -w /site jimmysong/istio-testing-website-builder:2018-06-15 scripts/lint_site.sh
>> 207 files are free from spelling errors
    content_zh/docs/setup/kubernetes/quick-start.md
      197 | >` 集群ID，您可以将 `acs-engine` 生成的 kubeconfig 文件从 `_output` 文件夹复制到您的机器中：

>> 1 spelling error found in 10 files
make: *** [lint] Error 1
```
How to exclude `kubeconfig` from spelling checking?

**Comment by geeknoid** [comment]
The file .spelling in the root of the repo contains dictionary exceptions. It's shared across all languages, which is a bit strange.

Also, in general words like kubeconfig should be in backticks. Stuff in backticks is rendered as a code block and is excluded from spell checking: `kubeconfig`

**Comment by rootsongjc** [comment]
After making `kubeconfig`  with backticks around`make lint` completed.

**Pull request merged**
