### PR TITLE
Rename target to destination

### PR DESCRIPTION
**Pull request by kyessenov**
This is the first step in the sequence of renaming operations:
1. rename canonical list
2. rename API symbols
3. rename code references to the API and samples
4. update docs

### CODE REVIEW

**Comment by kyessenov** [comment]
closing this per @smawson 's request until we all agree on the name of this attribute space.

**Comment by ldemailly** [comment]
what have we concluded?

**Comment by smawson** [comment]
After much discussion we concluded to go ahead and rename to destination.

**Comment by ldemailly** [comment]
cool. we may want to wait for more of the 0.2 meat to be in the website to merge but otherwise it should happen (maybe next week). reopening

**Pull request merged**
