### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by zonghaishang**
fix `request.code` to `response.code`

### CODE REVIEW

**Comment by rootsongjc** [comment]
@zonghaishang Please sign the CLA first.

**Comment by zonghaishang** [comment]
I signed it!

**Comment by zonghaishang** [comment]
error log:
```
- ./public/help/faq/general/index.html
  *  External link https://www.apache.org/licenses/LICENSE-2.0.html failed: got a time out (response code 0)
```

@rootsongjc  please trigger ci again, thanks.

**Comment by rootsongjc** [comment]
This is not a true error. Please submit a new commit to trigger the CI.

**Pull request merged**
