### PR TITLE
Update auth image to make is spiffe compatible

### PR DESCRIPTION
**Pull request by wattli**

### CODE REVIEW

**Comment by wlu2016** [comment]
lets wait after the VSID doc is finalized?

**Comment by wattli** [comment]
@wlu2016 , okay, i will hold, Yang actually asked this in VSID doc.

The file name does not change, so we don't need to update the concept doc.

**Comment by wlu2016** [comment]
vsid doc is updated now, I think this PR is good to go

**Comment by wattli** [comment]
@geeknoid , could you take a look please?

**Comment by lookuptable** [comment]
Vipin left some comments in the VSID doc. Let's again wait a bit to make sure things are settle please.

**Comment by lookuptable** [comment]
@wlu2016 has signed off and this is ready to be merged.

**Pull request merged**
