### PR TITLE
Link to bookinfo.sidecars.yaml is broken

### PR DESCRIPTION
**Pull request by danielmenezesbr**
ie: https://raw.githubusercontent.com/istio/istio/release-0.8/samples/bookinfo/consul/bookinfo.sidecars.yaml
or
https://raw.githubusercontent.com/istio/istio/release-0.8/samples/bookinfo/eureka/bookinfo.sidecars.yaml

### CODE REVIEW

**Comment by danielmenezesbr** [comment]
I signed it!

**Comment by geeknoid** [comment]
@rshriram Is those links are broken, it would indicate our directions depend on a file that doesn't exist. Any idea what the right fix here is?

**Comment by rshriram** [comment]
They are broken because those files are generated from a template in consul/templates/bookinfo.sidecars.yaml.tmpl .. how are the kubernetes files linked ?

**Comment by rshriram** [comment]
Yeah kube files are generated via istioctl

**Pull request merged**
