### PR TITLE
Added namespace when create helm template.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @sdake

### CODE REVIEW

**Comment by gyliu513** [comment]
@geeknoid @linsun can we have this merged, it is really not convenient that I have to copy the command from document and update the command again when doing the test.

**Comment by sdake** [comment]
@gyliu513 this should go into release 0.8.  Can you submit a PR against that branch?

**Comment by gyliu513** [comment]
@sdake I think we do not have 0.8 branch cut yet for document, seems we still need merge this to master?

@linsun @geeknoid please help confirm, thanks.

**Pull request merged**
