### PR TITLE
update instructions to use istio-ingress, zipkin

### PR DESCRIPTION
**Pull request by stevemcghee**
the instructions seem out of date, based on the DM template now.  hope this helps.

### CODE REVIEW

**Comment by geeknoid** [comment]
@salrashid123 Can you take a look please?

**Comment by salrashid123** [comment]
@stevemcghee  Thanks for filing and the PR
We recently (as of yesterday), updated the link to match DM template docs the instructions match ```release-0.8```.  I suspect when you ran it, we still hadn't updated the link so what you got out of the DM template was pre ```0.8``` istio.   If you run the dm template now, you should see what is matching in the docs.


- However, i did just now notice the quickstart guide doens't even set up ```jaeger```...(it still uses what we had before ```zipkin```).  I'll file a PR to update the actual istio DM next week,,,

**Comment by salrashid123** [comment]
@stevemcghee   once PR https://github.com/istio/istio/pull/6134  is done to fix tracing, we'll need some minor changes to the docs (i.,e the services would list stuff like ```deploy/istio-tracing```.

If you want to, you can update via PR once the one i filed is done.

If you want to test the template, i've staged it [here](https://console.cloud.google.com/launcher/config?templateurl=https://raw.githubusercontent.com/salrashid123/deploymentmanager-samples/master/istio_dm/istio-cluster.jinja)  on my git repo.

**Comment by stevemcghee** [comment]
sounds like you've got this covered.  ill bail on this one.

**Pull request closed without merging**
