### PR TITLE
Adding Alpha status SolarWinds adapter

### PR DESCRIPTION
**Pull request by leecalcote**

### CODE REVIEW

**Comment by geeknoid** [comment]
@jasmine-jaksic @jasminejaksic you ok adding stuff in this table?

**Comment by jasmine-jaksic** [comment]
@geeknoid Apologies for the delay. As long as it meets the [alpha criteria](https://github.com/istio/community/blob/master/FEATURE-LIFECYCLE.md), I'm fine with adding this to the features list.

**Comment by leecalcote** [comment]
@jasmine-jaksic @geeknoid thank you!

**Pull request merged**
