### PR TITLE
IBM Cloud Public quickstart

### PR DESCRIPTION
**Pull request by Rachael-Graham**
* Created 1 quickstart index page for all of IBM Cloud
* Used tabs for ICP and IBM Cloud Public
* Added steps for quickstart on IBM Public
* Changed name of directory from `quick-start-icp` to `quick-start-ibm` & moved icp image files into this new folder

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit fe4cf5da16d73dc5646d5454f07e5d849e6dad18

https://app.netlify.com/sites/preliminary-istio/deploys/5b898cbbdd28ef31e46b4908

**Comment by Rachael-Graham** [comment]
@geeknoid Hi there--tried out your new tab functionality, but it looks like the markdown in each tab isn't rendering. Thoughts? https://deploy-preview-2485--preliminary-istio.netlify.com/docs/setup/kubernetes/quick-start-ibm/

**Comment by frankbu** [comment]
There seem to be several blank lines in front of every diagram under the IBM Cloud Private tab, but otherwise looks good

**Comment by Rachael-Graham** [comment]
@frankbu yeah, I just tried a few things to see if I could fix it but no luck.

**Pull request merged**
