### PR TITLE
Trimming install task. remove redundant content

### PR DESCRIPTION
**Pull request by rshriram**

### CODE REVIEW

**Comment by rshriram** [comment]
ignoring presubmit errors for lyft.github.io since we will make a separate pass for that.

**Comment by rshriram** [comment]
170 and 193 are being removed right?
Also, I couldn't easily remove the others because there is no associated task for grafana/service graph

**Comment by frankbu** [comment]
No, I mean the new lines 170 and 193, after your deletions. I fixed them.

**Comment by ldemailly** [comment]
can you describe why the removal ?
cc @andraxylia who works on install and @douglas-reid for zipkin/jaeger

**Comment by douglas-reid** [comment]
Is this because we have a task on Distributed Tracing as well?

**Pull request merged**
