### PR TITLE
Translate: Istio Soft Multi-tenancy Support

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit 9152fcf00a902aae5667f8d4103551739b799477

https://app.netlify.com/sites/preliminary-istio/deploys/5b2361d4b13fb152d23e55e0

**Comment by geeknoid** [comment]
Due to changes in circleci+netlify, please rebase this PR and push again.

Thanks.

**Comment by geeknoid** [comment]
It doesn't appear as though the rebase worked. Your repo needs to contain the .circleci/config.yml file in it...

**Comment by fleeto** [comment]
@geeknoid  Oh i see now. I'll close these two pr and re-create them.

**Pull request closed without merging**
