### PR TITLE
Fix telemetry docs for 0.5.1 Prometheus

### PR DESCRIPTION
**Pull request by salrashid123**
```0.5.1``` config for Prometheus is missing the namespace [#3139](https://github.com/istio/istio/issues/3149)

Added in instructions to modify ```prometheus.yaml``` file.

I'll revert this change once ```0.6.0``` is out

### CODE REVIEW

**Comment by ldemailly** [comment]
so this should go in the release-0.5 branch then?
cc @geeknoid

**Comment by salrashid123** [comment]
@geeknoid   Is this ok to merge in or if  ```0.6.0``` is coming out next week, i can abandon this PR. LMK

**Comment by geeknoid** [comment]
I think might as well abandon at this point. 0.6 is actually done at this point, we're just waiting for the release notes to be finished before sending out the announcement.

**Comment by salrashid123** [comment]
SGTM.  i'll review the GKE install istio docs next week and see if there is a way to provide a self-contained 'copy-paste' command set like [this](https://github.com/salrashid123/istio_helloworld#create-a-19-gke-cluster-and-bootstrap-istio)

**Pull request closed without merging**
