### PR TITLE
translation: soft multitenancy

### PR DESCRIPTION
**Pull request by fleeto**

### CODE REVIEW

**Comment by geeknoid** [comment]
@rootsongjc Please review.

**Comment by geeknoid** [comment]
Hi, I did some refactoring and the file you edited has moved in the repo. Please rebase and push again. Sorry for the inconvenience.

**Comment by fleeto** [comment]
It's ok , just waiting for #1602 , after it closed , I'll correct related files, not only mine.

**Comment by fleeto** [comment]
It seems something wrong in the master.  This pr is blocked by ci, after merged with the master. So I'll merge again tonight or tomorrow.

**I think what we need most now is content**

**Pull request merged**
