### PR TITLE
Rewrite Rule configuration intro and some minor copy edits.

### PR DESCRIPTION
**Pull request by sgilsonapigee**
Signed-off-by: Stephen Gilson <gilsonsm@google.com>

### CODE REVIEW

**Comment by sgilsonapigee** [comment]
@sdake "operator" doesn't convey that it is the person using/configuring/administrating Istio that is doing the work. It implies some other entity is responsible for doing the configuration. Also, from the Istio style guide, the preference is to address the reader as "you" in the doc, which is a standard convention.

-Stephen

**Comment by geeknoid** [comment]
We've had guidelines for ever about using "you" instead of "we" throughout the site. Our tech writing friends have been purging uses of "we" they find as they go through the site.

"Operators" and "Users" fall in the same bucket IMO. We are addressing the text to the reader, they are the operators. So it seems reasonable to use "you" for this case as well.

Of course, I'm not a tech writer, and am not a native English speaker. So what do I know :-) But that's the motivation.

**Pull request merged**
