### PR TITLE
fix egress tcp _

### PR DESCRIPTION
**Pull request by loverto**

### CODE REVIEW

**Comment by sdake** [comment]
@loverto - your PR appears empty (in the files tab).

**Comment by rootsongjc** [comment]
@loverto CI failed, to fix this please rebase the master.
```
- ./public/docs/setup/kubernetes/sidecar-injection/index.html
  *  External link https://kubernetes.io/docs/admin/admission-controllers/#validatingadmissionwebhook-alpha-in-18-beta-in-19 failed: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ exists, but the hash 'validatingadmissionwebhook-alpha-in-18-beta-in-19' does not
  *  External link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#mutatingwebhookconfiguration-v1beta1-admissionregistration failed: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/ exists, but the hash 'mutatingwebhookconfiguration-v1beta1-admissionregistration' does not
htmlproofer 3.9.1 | Error:  HTML-Proofer found 2 failures!
```

**Pull request merged**
