### PR TITLE
Added steps for install istio with helm charts.

### PR DESCRIPTION
**Pull request by gyliu513**

### CODE REVIEW

**Comment by linsun** [comment]
We also need to ensure istio non-auth and auth configuration is exposed via chart, and even perhaps istio add-ons.

**Comment by gyliu513** [comment]
OK, will re-visit this once https://github.com/kubernetes/charts/issues/1909 got fixed.

**Comment by ldemailly** [comment]
closing this for now - we'll reopen once it's ready/working

**Comment by gyliu513** [comment]
https://github.com/kubernetes/charts/issues/1909 is now merged @linsun @ldemailly @rshriram 

There is also a PR bumping istio to 0.2.7 https://github.com/kubernetes/charts/pull/2392

**Comment by ldemailly** [comment]
We need to hear from a core contributor about their experience using helm before we send users to helm for 0.2 in this first release

**Comment by gyliu513** [comment]
@ldemailly I will try to contact some core contributor to have a try

**Comment by ldemailly** [comment]
@andraxylia volunteered to try

**Comment by gyliu513** [comment]
@linsun @rshriram @ldemailly any of you who is interested to try this? Both myself and @lachie83 are willing to help, we can even show you a walkthrough case.

**Comment by linsun** [comment]
me, i'll try this tmr. :)

**Comment by linsun** [comment]
sorry I had thought this is very easy, but I'm getting this error:

```
Lins-MacBook-Pro:Downloads linsun$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
"incubator" has been added to your repositories
Lins-MacBook-Pro:Downloads linsun$ helm install --name istio incubator/istio --namespace istio-system
Error: file "incubator/istio" not found
```

**Comment by linsun** [comment]
@gyliu513 @lachie83 ^^

**Comment by gyliu513** [comment]
@linsun I was always test as follows:

1) Check out `kubernetes/charts` code.
2) Go to `charts/` folder.
3) `helm install incubator/istio`

This works well, will check what is wrong with adding a repo, not sure if it is related to https://github.com/kubernetes/charts/tree/master/incubator/istio#installing-the-chart , the istio install now requires two steps, cc @lachie83

**Comment by linsun** [comment]
hmm, I had thought the istio helm chart is already published to the incubator repo thus I can just install it from the repo.  I think that is an easier step than git clone all charts.  Waiting for input from @lachie83

**Comment by lachie83** [comment]
@linsun this is due to the current helm chart version format being identified as a prerelease under semverv2. You need to run an install with the following flag `--devel`. This flag allows installation of prereleased versions More details in the following ticket about potentially changing the chart version

**Comment by lachie83** [comment]
Here is the related issue - https://github.com/kubernetes/helm/issues/3009

**Comment by linsun** [comment]
@lachie83 - It seems odd to run it with the flag --devel now that istio 0.2.7 is announced as the 0.2 release.   It is just a better user experience as no one would expect that --devel flag now.

**Comment by lachie83** [comment]
@linsun totally agree. Once we determine the best path forward we can address

**Comment by geeknoid** [comment]
Do we still want this PR?

**Comment by frankbu** [comment]
Users do seem to want it, but there are some issues with the helm chart that would first need to be fixed before we document it as an endorsed way to install Istio. Here is one I noticed: https://github.com/kubernetes/charts/issues/2508

**Comment by ldemailly** [comment]
there is also https://github.com/istio/istio/pull/2030 now

**Comment by sdake** [comment]
@sbezverk I was just taking a look at this PR, and thought you may want to document in the Istio website how to use the istio repo based helm charts.

**Comment by sbezverk** [comment]
@sdake Once I got everything working, I will definitely post helm deployment document.

**Comment by gyliu513** [comment]
Thanks @sbezverk , please let me know when your PR is ready.

**Pull request closed without merging**
