### PR TITLE
Translate V1alpha3 routing introduction blog to Chinese

### PR DESCRIPTION
**Pull request by zhaohuabing**
Signed-off-by: Huabing Zhao <zhaohuabing@gmail.com>

### CODE REVIEW

**Comment by zhaohuabing** [comment]
CircleCI test failed because of some links not in the files of this PR. I checked these links are reachable. Any idea?

- ./public/about/notes/0.2/index.html
  *  External link https://kubernetes.io/docs/admin/extensible-admission-controllers/ failed: 404 No error
- ./public/docs/tasks/traffic-management/circuit-breaking/index.html
  *  External link https://archive.istio.io/v0.7/docs/tasks/traffic-management/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
- ./public/help/bugs/index.html
  *  External link https://preliminary.istio.io/ failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: SSL connect error
htmlproofer 3.9.1 | Error:  HTML-Proofer found 3 failures!

**Comment by gyliu513** [comment]
@zhaohuabing this failure does not seem related to your PR?

**Comment by zhaohuabing** [comment]
@gyliu513 No, not at all. 
I suggest The CI should check only the links in the files of the PR rather than checking all the files.

**Comment by gyliu513** [comment]
@geeknoid do you know why CI keeps failing? All of the files that CI report cannot find does exist.

**Comment by zhaohuabing** [comment]
@gyliu513 Is there anything I can do in order to merge this PR?

**Comment by gyliu513** [comment]
@zhaohuabing not sure why CI fails, let's wait some comments from @geeknoid 

BTW: I have just re-run the CI.

**Comment by zhaohuabing** [comment]
@geeknoid  It seems this broken link at ./public/blog/2018/egress-tcp/index.html which is blocking PRs.
  *  External link https://dev.mysql.com/doc/refman/5.7/en/mysqlsh.html failed: 404 No error

**Pull request merged**
