### PR TITLE
Add "COOHOM" logo into customers

### PR DESCRIPTION
**Pull request by oreasono**
Add the company logo on customers page.

### CODE REVIEW

**Comment by rootsongjc** [comment]
@oreasono Please sign the CLA.

**Comment by oreasono** [comment]
I signed it!

**Comment by oreasono** [comment]
@rootsongjc signed CLA and request for approval

**Comment by oreasono** [comment]
@rootsongjc Thanks for this nice clarify. I am the tech lead of coohom.com's team. We were digging around Istio since January, And we are running Istio 1.0.1 on our production environment(https://www.coohom.com), test and dev environment.

**Pull request merged**
