### PR TITLE
Add missing feature links

### PR DESCRIPTION
**Pull request by john-a-joyce**
This change adds some missing links to the feature-stages page

### CODE REVIEW

**Comment by john-a-joyce** [comment]
CC @geeknoid - one of my links was bad as it was referencing a 0.7 location that moved.  So circelci failed I am fixing that now.

**Comment by john-a-joyce** [comment]
Opps merged already - I guess I will fix with a new PR

**Comment by geeknoid** [comment]
Hmmm, the merge should not have happened if CircleCi was broken.

**Comment by john-a-joyce** [comment]
When I checked Circleci was complaining about the APIkey URL because I was using a location that was only valid on the 0.7 release.   I was in the process of pushing a fix to correct that when the merge happened.  I will do another fix to get that,  but not sure why it was allowed to merge automatically

**Comment by john-a-joyce** [comment]
Nevermind - it looks like my commit to fix this just got in before your approval
I thought I missed it by a few minutes

**Pull request merged**
