### PR TITLE
New diagram for mesh expansion example

### PR DESCRIPTION
**Pull request by oaktowner**
Replaces the diagram at https://istio.io/docs/guides/integrating-vms/

(original is located in Community Drive -> Misc -> Drawings for Istio.io site)

### CODE REVIEW

**Comment by geeknoid** [comment]
Please update markdown to have the proper width and ratio values for revised images.

**Comment by linsun** [comment]
@oaktowner you have 2 boxes for reviews service... think one should be rating instead.  Also, do you think it will be better if we have all k8s services shown within k8s so it is clear which ones run in k8s?

**Pull request merged**
