### PR TITLE
Fixes bug #608 - Fixes image caption and size

### PR DESCRIPTION
**Pull request by bingoarun**
Added figcaption tag, removed width and removed notion of left and right

Fixes bug - https://github.com/istio/istio.github.io/issues/608

### CODE REVIEW

**Comment by bingoarun** [comment]
fireshot capture 1 - istio _ distributed tracing

**Comment by bingoarun** [comment]
@ldemailly : Yes, I checked. Attached the screenshot.

**Comment by ldemailly** [comment]
manually checked the 2 urls do work, merging

**Pull request merged**
