### PR TITLE
Change feature status of Helm to Beta

### PR DESCRIPTION
**Pull request by sdake**
The Helm implementation meets all endpoints for a Beta feature.

### CODE REVIEW

**Comment by sdake** [comment]
@costinm - if you agree, please let the approvers know, if not, let them know that too.

Cheers
-steve

**Comment by linsun** [comment]
can you be a beta without any test automation?  I think not.

**Comment by linsun** [comment]
https://github.com/istio/community/blob/master/FEATURE-LIFECYCLE-CHECKLIST.md

**Comment by sdake** [comment]
@linsun we test ```helm template``` several times on every PR.  If you mean do we test ```helm install``` in the gate, we don't.

**Comment by linsun** [comment]
yes, that is what i meant, which is the feature (helm-install) you want to promote to beta...

**Comment by sdake** [comment]
@linsun I look at the Helm implementation holistically.  Helm is used throughout Istio now in many ways - not just ```helm install```.  However, if a required check for ```helm install``` is the only gating factor, that seems fair to implement before Beta promotion.

What other things are relevant factors from the checklist are relevant from your point of view so we can get that job done prior to 0.9?

Cheers
-steve

**Comment by linsun** [comment]
@sdake I'm working on this PR which will cover some basic testing via helm install:  https://github.com/istio/istio/pull/5114

I think we need to do more docs and automated testing on using helm to do incremental adopt of istio.    There are a few bugs out there on certain configuration doesn't work.

Also, our istio upgrade should be replaced using helm template or install.  They are currently using the to be deprecated istio.yaml file shipped in the release.   https://istio.io/docs/setup/kubernetes/upgrading-istio.html

I welcome your thoughts too.

**Comment by sdake** [comment]
@linsun good work on the PR!  The outstanding work items sound reasonable to me in addition to an API review.

Is the typical process for moving from Alpha to Beta undefined from a mechanics point of view (IOW what do we do with github)?  Or is it as simple as creating an issue tracker with a checklist of work to be done?  If so, happy to create the issue tracker and close this PR.  If there is some other technique in use, please let me know so we don't lose track of the work needed

The main concern is Helm is a P0 feature on the features spreadsheet - indicating Istio will slip without Helm entering stable.

I wasn't aware of the short-form checklist (I had seen the other checklist that is linked in that document) and somehow missed the API review requirements.

I think the one thing that really needs to be done prior to Stable is a review and lockdown of the API model (the `values.yaml` file).  The checklist lists that as a beta requirement, however, in this case I suspect people will be modifying the API in the weeks prior to 1.0 so perhaps we can schedule an API review and sanitization for 0.9, and a second lockdown API review for 1.0.

Cheers
-steve

**Comment by geeknoid** [comment]
@jasmine-jaksic @jasminejaksic

**Comment by geeknoid** [comment]
@jasmine-jaksic @jasminejaksic Should we make this change, or close this PR?

**Comment by geeknoid** [comment]
Sadly, this one word change has a merge conflict. Steve, would you mind resolving?

Thanks.

**Comment by geeknoid** [comment]
I took care of this in a separate PR.

**Comment by sdake** [comment]
@geeknoid thanks.

**Pull request closed without merging**
