### PR TITLE
Add documentation for using Jaeger with Istio

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@rshriram sorry for the delay, just waiting for our legal team to give the go ahead, but shouldn't be an issue.

**Comment by objectiser** [comment]
I signed it!

**Comment by objectiser** [comment]
@rshriram I've been added to the Red Hat master CLA group, and added my redhat email to my github account - so hopefully it should all work, but if not let me know.

**Comment by objectiser** [comment]
I signed it!

**Comment by rshriram** [comment]
Merge with master

**Comment by rshriram** [comment]
I mean sync please

**Comment by objectiser** [comment]
Rebased.

**Comment by objectiser** [comment]
@rshriram Is there a problem with the presubmit check, seems to be stuck - not sure what it is doing? Or is there something else I need to do?

**Comment by christian-posta** [comment]
I've just verified the PR on the most recent builds of istio+bookinfo on GKE. Looks great!!

**Pull request merged**
