### PR TITLE
Update inject container name from istio-proxy to proxy.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/istio/istio.github.io/issues/430

### CODE REVIEW

**Comment by ayj** [comment]
`istio-proxy` is the correct container name in the master branch (see [here](https://github.com/istio/pilot/blob/master/platform/kube/inject/inject.go#L59)). `proxy` is only used by the 0.1 branch.

**Comment by gyliu513** [comment]
@ayj I think that we should update document to `proxy`, as the document will enable user to get the released version which is `proxy`, comments?

**Comment by ayj** [comment]
Can you rebase this fix against the release-0.1 branch which corresponds to the 0.1.x versions?

**Comment by gyliu513** [comment]
v0.1 document https://istio.io/v-0.1/docs/tasks/istio-auth.html using `proxy` instead and should works. @ayj

**Pull request closed without merging**
