### PR TITLE
Make the I in istio readable

### PR DESCRIPTION
**Pull request by ldemailly**
Verdana is a sans serif font - except it has a readable upper case I - see screenshots:

### CODE REVIEW

**Comment by ldemailly** [comment]
After/Before:

screen shot 2017-12-07 at 11 50 54 am

screen shot 2017-12-07 at 11 50 19 am

**Comment by ldemailly** [comment]
Survey:
https://docs.google.com/forms/d/e/1FAIpQLScfsO_ATK3rRj92mHaCsqTbfC2AU2wypJO5anLswjn8lG_gzw/viewanalytics

**Comment by linsun** [comment]
Agreed, there are lots of places that this logo and possibly font is used...

**Comment by ldemailly** [comment]
@zinuga from steering committee notes: "Punting discussion of Istio “I” to PM/product folks."
can you make a decision ?

**Comment by zinuga** [comment]
Main goal here should be consistency. cant have different fonts, colors, brand colors in different places for istio. I suggest we make readable upper case I as our default font and add a branding guidelines covering logo, text in our repo. Similar to this one.

https://github.com/kubernetes/kubernetes/blob/master/logo/usage_guidelines.md
I can get you some help from marketing to get this published.

**Comment by geeknoid** [comment]
So:

- I think our Twitter account already has a different font, which is
unfortunate.

- To get serifs on the I, we need a different font, here and elsewhere.

- We have an alternate brand logo available if we want to use it.

- Finally, I strongly suspect that this is not an actual problem. I haven't
heard of anyone actually getting confused by this. Heck, the web site is
istio.io. I think this is merely a theoretical concern.

What I'd like us to do at this point is make the Twitter font look like
what's on istio.io today and then leave things as-is. If we want, I can add
a popover so that if you hover the mouse over the name on istio.io, it
would show it in the popup using a serif font.

**Comment by ldemailly** [comment]
> I suggest we make readable upper case I as our default font

this is what this PR does and it's already readable/similar on twitter

so I think that means merge this rather than not

**Comment by zinuga** [comment]
lets merge this

**Pull request merged**
