### PR TITLE
New citadel (auth) diagram

### PR DESCRIPTION
**Pull request by oaktowner**
New diagram (used on https://istio.io/docs/concepts/security/mutual-tls/ )

### CODE REVIEW

**Comment by sdake** [comment]
@myidpt would you mind taking a quick look at https://deploy-preview-1929--preliminary-istio.netlify.com/docs/concepts/security/auth.svg and see if it looks correct?

Cheers
-steve

**Comment by linsun** [comment]
/LGTM

@oaktowner you have service-a in SPIFF url for service-b on the vm.

**Comment by myidpt** [comment]
The logic looks good to me. Thanks for updating the graph styles.

**Pull request merged**
