### PR TITLE
Add documentation about exporting logs from stackdriver to different sinks like bigquery

### PR DESCRIPTION
**Pull request by gargnupur**

### CODE REVIEW

**Comment by geeknoid** [comment]
Deploy preview for *preliminary-istio* failed.

Built with commit 387f06c4f479ddfb3a000d89f805db2bcd1c6db7

https://app.netlify.com/sites/preliminary-istio/deploys/5b0daa52dd6a5440967db5a0

**Comment by geeknoid** [comment]
Also, please rebase on the latest version of the source tree as files have moved to new locations.

**Comment by geeknoid** [comment]
This PR now says it has 492 files. Something's not right :-)

**Comment by gargnupur** [comment]
@geeknoid : Thanks for the review!

I tried re-basing and looks like that screwed up :(

I will send a new PR for this now...

**Pull request closed without merging**
