### PR TITLE
Update the Citadel certificate lifetime config document

### PR DESCRIPTION
**Pull request by lei-tang**
Update the Citadel certificate lifetime config document to be consistent with the implementation.

### CODE REVIEW

**Comment by geeknoid** [comment]
Please rebase and repush, this should fix all the CI errors.

**Comment by lei-tang** [comment]
Thanks! After the rebase, it passes the CI tests.

**Comment by sdake** [comment]
@myidpt sorry - this is what I get for doing reviews early before the morning caffeine.  If you would like a revert on this PR, LMK, and I'll do that.

For reference, many firms have big balls of red tape requiring the ability to set a maximum TTL on certificates (made up example: root certificates should have a 5 year maximum enforced by the software components).

**Comment by lei-tang** [comment]
@myidpt The default values in the document are inconsistent with the values in the code. Plus, if the values in the implementation change, it is not easy to find the values in this FAQ and update it. I will create a PR to add the default values of these command line options to the usage instructions for the commands.

**Comment by lei-tang** [comment]
The PR https://github.com/istio/istio/pull/7398 is created to add the default values of the command line options of Citadel and Node Agent to their command usage instructions.

**Pull request merged**
