### PR TITLE
Chinese: announcing istio 1.0

### PR DESCRIPTION
**Pull request by rootsongjc**
Translate announcing istio 1.0 to Chinese

### CODE REVIEW

**Comment by rootsongjc** [comment]
@geeknoid The Chinese homepage and Istio 1.0 announcement page look like not show the latest version? Can you fix it?

**Comment by geeknoid** [comment]
You mean on istio.io? Cause I do see it in preliminary.istio.io

To see it on istio.io, I need to cherry-pick from master.

**Comment by rootsongjc** [comment]
@geeknoid Of course istio.io, some people may visit the Chinese homepage directly, so we'd better fix it soon.

**Comment by geeknoid** [comment]
I did the cherry pick, the site should be updated in a few minutes

**Pull request merged**
