### PR TITLE
Create destination rules used by "reviews" and "ratings" virtual services in rate-limiting task

### PR DESCRIPTION
**Pull request by witlessbird**
Fixes https://github.com/istio/istio/issues/7285

### CODE REVIEW

**Comment by geeknoid** [comment]
Mandar is currently rewriting this page...

**Comment by witlessbird** [comment]
Sounds good; looks like there are issues with rate-limiting config too (possibly related to https://github.com/istio/istio/pull/6207). Please let me know if any help is required.

**Comment by witlessbird** [comment]
Also: should I close the PR?

**Comment by witlessbird** [comment]
As @frankbu pointed out the issue has been fixed by an update to bookinfo installation docs: https://preliminary.istio.io/docs/examples/bookinfo/#apply-default-destination-rules. I'm going to close the PR.

**Pull request closed without merging**
