### PR TITLE
Make description of Resolution phase to be explicit about resolved actions

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
the only resolved actions are currently invocations of handlers

### CODE REVIEW

**Comment by vadimeisenbergibm** [comment]
@geeknoid Sounds good, would love to read the blog post.

**Comment by geeknoid** [comment]
The blog post is on the site now:
https://istio.io/blog/mixer-adapter-model.html

**Comment by ldemailly** [comment]
ping?

**Comment by geeknoid** [comment]
As I said, I don't believe these changes are correct.

Handlers are not 'applied', they are used.

Additionally, the process involves more than just handlers. All types of Mixer config objects are selected based on the service, by virtue of the namespace.

**Comment by ldemailly** [comment]
I meant for vadim to update (or close) his pr

**Pull request closed without merging**
