### PR TITLE
New diagrams for /docs/guides/bookinfo

### PR DESCRIPTION
**Pull request by oaktowner**
Two new diagrams for the bookinfo example (https://istio.io/docs/guides/bookinfo/)

Originals in Community Folder (misc/Drawings for istio.io)

### CODE REVIEW

**Comment by sdake** [comment]
@rshriram would you take a quick look of the diagram change https://deploy-preview-1932--preliminary-istio.netlify.com/docs/examples/bookinfo/noistio.svg and https://deploy-preview-1932--preliminary-istio.netlify.com/docs/examples/bookinfo/withistio.svg

@oaktowner your diagrams look really good - thanks so much for the contributions!  The reason I am asking others to review them is they are domain experts in these areas, and want to be certain the diagrams are consistent with the implementation.

Mind I ask which diagramming tool you use?

Cheers
-steve

**Comment by rshriram** [comment]
Diagram looks good. two nits:
the ruby picture needs to be accompanied by the word Ruby, to explicitly indicate that Details is written in Ruby.

It would be helpful to add black stars for reviews-v2 and red stars for reviews-v3

**Comment by geeknoid** [comment]
Please update markdown to have the proper width and ratio values for revised images.

**Comment by linsun** [comment]
Looks good, 1 nit:  in the last right box of 2nd diagram, you had reviews for rating service.  Also, proxy icon was named as review or rating service incorrectly.

**Comment by sdake** [comment]
@geeknoid I'm unclear what has been happening with the ratios on these new SVGs and I'm not sure how to correctly evaluate them.  Can you provide further guidance so this review doesn't stall?

Cheers
-steve

**Comment by ymesika** [comment]
I actually liked the black/red stars in the Reviews v2/v3 which explained nicely what is the differences between the v1/v2/v3 reviews version. They are missing from the new diagrams though.

**Comment by frankbu** [comment]
I agree with @ymesika about the stars should be in the diagram.

Also, the diagram without Istio should not have the Ingress on the left side, because that's not part of the application, it's part of a k8s deployment of the app. The app is generic, can run on any platform.

**Comment by geeknoid** [comment]
@oaktowner Hey Dan, do you have some time to address the feedback?

**Comment by geeknoid** [comment]
Closing for now, please resubmit if you'd like to proceed.

**Pull request closed without merging**
