### PR TITLE
zh: fix content_zh/docs/examples/bookinfo/index.md

### PR DESCRIPTION
**Pull request by supereagle**
Update zh doc of https://preliminary.istio.io/docs/examples/bookinfo/#if-you-are-running-on-kubernetes

### CODE REVIEW

**Comment by supereagle** [comment]
I signed it!

**Comment by rootsongjc** [comment]
@supereagle Please sign the CLA first and fix the CI errors.

**Comment by supereagle** [comment]
I signed it!

**Comment by supereagle** [comment]
I have signed the CLA, but the issue still not passes the CLA check, not sure the reason. Maybe need to wait for some time.

CI failure will be fixed in #2559

**Comment by supereagle** [comment]
I signed it!

**Comment by rootsongjc** [comment]
CI failed, please re-lint.
```bash
git commit --allow-empty -m "re-lint"
git push origin update-example
```

**Pull request merged**
